spring:
  profiles:
    active: dev
  redis:
    host: 192.168.72.139
    port: 6380
    database: 0
    timeout: 1800000ms
    password: itmallredis
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
#此模块不需要数据源
#  datasource:
#    url: jdbc:mysql://192.168.72.139:3330/itaomall?characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: rootitmall
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  elasticsearch:   //这里用自己配置的高级rset客户端，暂不用springboot自动配置的
#      jest:
#        uris: http://1.12.223.197:9200
#      rest:
#        uris: http://1.12.223.197:9200

swagger2:
  enabled: true  #开启swagger2
#自定义es高级rest客户端RestHighLevelClient
es:
  host: 192.168.72.139
  port: 9200


